### ISSUE TITLE
Getting error while using this action

### ISSUE THREAD

**Issue by npaulkr** [ietf-tools/semver-action#22]
Hello,
I want to bump my semver version when I merge my PR.
I was trying your action like this:
```
- name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
```
and I got an error:
```
Run ietf-tools/semver-action@v1
Comparing against latest tag: v2.4.0
/home/runner/work/_actions/ietf-tools/semver-action/v1/dist/index.js:4998
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/ietf-tools/semver-action/v1/dist/index.js:4998:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/runner/work/_actions/ietf-tools/semver-action/v1/dist/index.js:31114:24) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/krogertechnology/in-store-agent/compare/v2.4.0...main?page=1&per_page=100',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 16 Jan 2023 09:32:29 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'BC09:371B:4695AA0:90EDAA7:63C5[19](https://github.com/krogertechnology/in-store-agent/actions/runs/3929009536/jobs/6717298461#step:6:20)AD',
      'x-ratelimit-limit': '15000',
      'x-ratelimit-remaining': '14998',
      'x-ratelimit-reset': '1673864780',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '2',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/commits/commits#compare-two-commits'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/krogertechnology/in-store-agent/compare/v2.4.0...main?page=1&per_page=100',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/16.13.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/krogertechnology/in-store-agent/actions/runs/3929009536/jobs/6717298461#step:6:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/krogertechnology/in-store-agent/actions/runs/3929009536/jobs/6717298461#step:6:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/krogertechnology/in-store-agent/actions/runs/3929009536/jobs/6717298461#step:6:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  }
}
```
Can you help me with the problem please?

**Comment by NGPixel** [comment]
You're either missing at least 1 tag in your repo or the branch you specified doesn't exist. Do you actually have a branch named `main`?
